jwglxt/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.views.generic.base import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_judge/', views.login_judge),
    path('', views.login),
    path('student_information_fix/', views.student_information_fix),
    path('student_submit_fix/', views.student_submit_fix),
    path('teacher_submit_fix/', views.teacher_submit_fix),
    url('login_judge/(\d+)([a-z])/$', views.student_information_fix, name='fix'),
    path('find_grade/', views.find_grade),
    path('find_schedule/', views.find_schedule),
    path('find_course_schedule/', views.find_course_schedule),
    path('find_course/', views.find_course),
    path('admin_find_course/', views.admin_find_course),
    path('add_course/', views.add_course),
    path('select_course/', views.select_course),
    path('cancel_select/', views.cancel_select),
    path('is_admin/', views.is_admin),
    url('is_admin/(\d+)/$', views.admin, name='admin'),
    path('add_notice/', views.add_notice),
    path('grade_manage/', views.grade_manage),
    path('update_grade/', views.update_grade),
    path('find_student/', views.find_student),
    path('add_student/', views.add_student),
    path('add_teacher/', views.add_teacher),
    path('arrange_course/', views.arrange_course),
    path('find_arranged_course/', views.find_arranged_course),
    path('delete_arranged_course/', views.delete_arranged_course),
    path('student_change_password/', views.student_change_password),
    path('teacher_change_password/', views.teacher_change_password),
    url(r'favicon.ico/', RedirectView.as_view(url=r'/static/image/favicon.ico')),
]

app/models.py
from django.db import models

class Student(models.Model):

    '''学生信息表'''

    student_id = models.CharField(max_length=20, verbose_name='学号', primary_key=True, unique=True, db_index=True)
    student_name = models.CharField(max_length=20, verbose_name='姓名', null=True)
    student_age = models.PositiveSmallIntegerField(verbose_name='年龄', null=True)
    student_sex = models.CharField(max_length=20, default='男', verbose_name='性别', null=True)
    student_nation = models.CharField(max_length=20, default='汉族', verbose_name='民族', null=True)
    student_political_status = models.CharField(max_length=20, default='群众', verbose_name='政治面貌', null=True)
    student_come_year = models.CharField(max_length=40, verbose_name='入学日期', null=True)
    student_college = models.CharField(max_length=20, default='信息科学与技术学院', verbose_name='学院', null=True)
    student_major = models.CharField(max_length=20, verbose_name='专业', null=True)
    student_class = models.CharField(max_length=20, verbose_name='班级', null=True)
    student_province = models.CharField(max_length=20, verbose_name='省份', null=True)
    student_city = models.CharField(max_length=20, verbose_name='城市', null=True)
    student_birthday = models.CharField(max_length=40, verbose_name='出生日期', null=True)
    #student_phone = models.CharField(max_length=20, verbose_name='手机号码', null=True)
    student_qq = models.CharField(max_length=20, verbose_name='QQ号码', null=True)
    student_wechat = models.CharField(max_length=20, verbose_name='微信号码', null=True)
    #student_email = models.EmailField(verbose_name='邮件地址', null=True)
    student_high_school = models.CharField(max_length=20, verbose_name='毕业高中', null=True)
    student_foreign_language = models.CharField(max_length=20, default='英语', verbose_name='外语', null=True)
    student_status = models.CharField(max_length=20, default='在读', verbose_name='状态', null=True)
    #student_image

    class Meta:
        verbose_name = '学生信息表'
        verbose_name_plural = verbose_name

class Teacher(models.Model):

    '''教师信息表'''

    teacher_id = models.CharField(max_length=20, verbose_name='工号', primary_key=True, unique=True, db_index=True)
    teacher_name = models.CharField(max_length=20, verbose_name='姓名', null=True)
    teacher_age = models.PositiveSmallIntegerField(verbose_name='年龄', null=True)
    teacher_sex = models.CharField(max_length=20, default='男', verbose_name='性别', null=True)
    teacher_nation = models.CharField(max_length=20, default='汉族', verbose_name='民族', null=True)
    teacher_political_status = models.CharField(max_length=20, default='群众', verbose_name='政治面貌', null=True)
    teacher_department = models.CharField(max_length=20, verbose_name='学院', default='信息科学与技术学院', null=True)
    teacher_academic_title = models.CharField(max_length=20, default='教授', verbose_name='职称', null=True)
    teacher_degree = models.CharField(max_length=20, default='学士', verbose_name='学位', null=True)
    teacher_come_year = models.CharField(max_length=80, verbose_name='入职日期', null=True) #去掉time
    teacher_province = models.CharField(max_length=20, verbose_name='省份', null=True)
    teacher_city = models.CharField(max_length=20, verbose_name='城市', null=True)
    teacher_birthday = models.CharField(max_length=255, verbose_name='出生日期', null=True) #去掉time
    #teacher_phone = models.CharField(max_length=20, verbose_name='手机号码', null=True)
    teacher_qq = models.CharField(max_length=20, verbose_name='QQ号码', null=True)
    teacher_wechat = models.CharField(max_length=20, verbose_name='微信号码', null=True)
    #teacher_email = models.EmailField(verbose_name='邮件地址', null=True)
    teacher_graduate_school = models.CharField(max_length=20, verbose_name='毕业院校', null=True)

    class Meta:
        verbose_name = '教师信息表'
        verbose_name_plural = verbose_name

class Course(models.Model):
    '''课程信息表'''
    course_id = models.CharField(max_length=20, verbose_name='课程号', primary_key=True, unique=True, db_index=True)
    course_name = models.CharField(max_length=20, verbose_name='课程名', unique=True)
    course_status = models.CharField(max_length=20, default='未开', verbose_name='课程状态')
    course_college = models.CharField(max_length=20, default='信息科学与技术学院', verbose_name='开课学院')
    course_pre_id = models.CharField(max_length=20, verbose_name='先修课程号', null=True)
    course_pre_name = models.CharField(max_length=20, verbose_name='先修课程名', null=True)
    course_introduction = models.CharField(max_length=1000, verbose_name='课程介绍')
    course_scale = models.CharField(max_length=20, verbose_name='平时成绩比例')
    course_volume = models.CharField(max_length=20, verbose_name='课程容量')

    class Meta:
        verbose_name = '课程信息表'
        verbose_name_plural = verbose_name

class SelectCourse(models.Model):
    '''选课表'''
    student_id = models.ForeignKey(to='Student', on_delete=models.DO_NOTHING, verbose_name='学号')
    term = models.CharField(max_length=20, verbose_name='学期')
    course_id = models.ForeignKey(to='Course',  on_delete=models.DO_NOTHING, verbose_name='课程号')
    teacher_id = models.ForeignKey(to='Teacher', on_delete=models.DO_NOTHING, verbose_name='工号')
    student_usual_grade = models.CharField(max_length=20, verbose_name='平时成绩')
    student_final_grade = models.CharField(max_length=20, verbose_name='期末成绩')
    student_total_grade = models.CharField(max_length=20, verbose_name='总评成绩')

    class Meta:
        verbose_name = '选课表'
        verbose_name_plural = verbose_name
        unique_together = ('student_id', 'term', 'course_id', 'teacher_id')

class CourseArrangement(models.Model):
    '''课程安排表'''
    course_id = models.ForeignKey(to='Course', on_delete=models.DO_NOTHING, verbose_name='课程号')
    term = models.CharField(max_length=20, verbose_name='学期')
    teacher_id = models.ForeignKey(to='Teacher', on_delete=models.DO_NOTHING, verbose_name='工号')
    week = models.CharField(max_length=20, verbose_name='周次')
    session = models.CharField(max_length=20, verbose_name='节次')
    location = models.CharField(max_length=20, verbose_name='地点')
    weekday = models.CharField(max_length=20, verbose_name='上课日期')

    class Meta:
        verbose_name = '课程安排表'
        verbose_name_plural = verbose_name
        unique_together = ('course_id', 'term', 'teacher_id',)

class Notice(models.Model):
    '''公告表'''
    notice_id = models.AutoField(primary_key=True)
    notice_send_time = models.DateTimeField(auto_now_add=True, verbose_name='发送日期')
    notice_content = models.CharField(max_length=1000, verbose_name='通知内容')
    notice_title = models.CharField(max_length=255, verbose_name='通知标题')

    class Meta:
        verbose_name = '公告表'
        verbose_name_plural = verbose_name

class User(models.Model):
    '''用户登录表'''
    account = models.CharField(max_length=20, verbose_name='账号')
    name = models.CharField(max_length=20, verbose_name='姓名')
    identity = models.CharField(max_length=20, default='学生', verbose_name='身份')
    password = models.CharField(max_length=32, verbose_name='密码')
    phone = models.CharField(max_length=11, verbose_name='手机号码', unique=True)
    email = models.EmailField(verbose_name='邮件地址', unique=True)

    class Meta:
        verbose_name = '用户登录表'
        verbose_name_plural = verbose_name
        unique_together = ('account', 'identity',)
'''
class SchoolTerm(models.Model):
    学期表（搁置）
    begin_year = models.CharField(max_length=20, verbose_name='开始年份')
    end_year = models.CharField(max_length=20, verbose_name='结束年份')
    number = models.IntegerField(verbose_name='学期号')

    class Meta:
        verbose_name = '学期表'
        verbose_name_plural = verbose_name
        unique_together = ('begin_year', 'end_year', 'number',)

class Message(models.Model):
    消息表(搁置)
    message_id = models.CharField(max_length=20, verbose_name='消息号', primary_key=True, unique=True, db_index=True)
    student_id = models.ForeignKey(Student, on_delete=models.DO_NOTHING, verbose_name='学号')
    message_content = models.CharField(max_length=1000, verbose_name='消息内容')
    message_send_time = models.DateTimeField(auto_now_add=True, verbose_name='发送日期')
    message_status = models.CharField(max_length=20, verbose_name='消息状态')
    message_title = models.CharField(max_length=255, verbose_name='消息标题')

    class Meta:
        verbose_name = '消息表'
        verbose_name_plural = verbose_name

class SelectList(models.Model):
    选课清单表
    major =  models.CharField(max_length=20, verbose_name='专业')
    term = models.CharField(max_length=20, verbose_name='学期')
    course_id = models.ForeignKey(Course, on_delete=models.DO_NOTHING, verbose_name='课程号')
    status = models.CharField(max_length=20, verbose_name='状态')
    volume = models.IntegerField(verbose_name='容量')

    class Meta:
        verbose_name = '选课清单表'
        verbose_name_plural = verbose_name
        unique_together = ('major', 'term',)
'''

app/templates/teacher/add_notice.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8"/>
    <title>发布公告</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body{
            background-color: rgb(240, 240, 240);
        }
    </style>
</head>
<body>
    {% if is_add %}
        <script>
            window.onload=function () {
                alert("发布成功！")
            }
        </script>
    {% endif %}
    <div style="background: #0483d4; border: 1px solid #e7e7e7;line-height: 60px; margin-bottom: 15px">
        <img src="{% static 'image/logo_jw_w2.png' %}" style="padding-left: 80px">
        <span style="color: white; font-size: 25px; vertical-align: middle">发布公告</span>
    </div>
    <!--top_end-->
    <div class="container" style="margin-left: 70px; margin-top: 1px; padding: 0px; margin-right: 70px; width: auto; background-color: white; height: 600px;">
        <div class="row">
            <form action="/add_notice/" method="post">
                {% csrf_token %}
                <div class="col-md-12" style="line-height: 25px;border: 1px solid #eeeeee;">
                    <h5 style="font-size: 30px; font-family: 'Microsoft Yahei'; margin-bottom: 20px; ">请输入公告内容</h5>
                    <div class="col-md-8">
                    <input type="text" name="title" placeholder="请输入公告标题" class="form-control" style="margin-bottom: 20px;" required>
                    </div>
                    <div class="col-md-4"></div>
                </div>
                <div class="col-md-12" style="margin-top: 20px">
                    <div class="col-md-8">
                    <textarea name="content" placeholder="请输入公告内容" class="form-control" required style="height: 300px;"></textarea>
                        <div class="col-md-10"></div>
                        <div class="col-md-2">
                            <button type="submit" class="btn btn-primary btn-block pull-right" style="margin-top: 40px">发布公告</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="footer" style="padding: 25px">
	<p style="text-align: center; color: rgb(128, 153, 175)">版权所有&copy; Copyright 1999-2017  正方软件股份有限公司　　中国·杭州西湖区紫霞街176号 互联网创新创业园2号301</p>
    </div>
</body>
</html>

app/templates/teacher/add_student.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8"/>
    <title>添加学生</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body{
            background-color: rgb(240, 240, 240);
        }
    </style>
</head>
<body>
    {% if is_add %}
        <script>
            window.onload=function () {
                alert("添加成功！")
            }
        </script>
    {% endif %}
    <div style="background: #0483d4; border: 1px solid #e7e7e7;line-height: 60px; margin-bottom: 15px">
        <img src="{% static 'image/logo_jw_w2.png' %}" style="padding-left: 80px">
        <span style="color: white; font-size: 25px; vertical-align: middle">添加学生</span>
    </div>
    <!--top_end-->
    <div class="container" style="margin-left: 70px; margin-top: 1px; padding: 0px; margin-right: 70px; width: auto">
        <form action="/add_student/" method="post">
        {% csrf_token %}
            <div class="row" style="background: white; margin-top: 15px;">
                <div class="col-md-12" style="border-bottom: 1px solid #eeeeee; font-weight: bold; font-size: 20px; padding: 5px; line-height: 80px;">
                    <center>添加学生</center>
                </div>
                <div class="col-md-4" >
                    <ul style="list-style: none">
                        <li>
                            <h4>学号:</h4>
                            <span><input type="text" class="form-control" name="student_id" required autocomplete="off"></span>
                        </li>
                        <li>
                            <h4>性别:</h4>
                            <span>
                                <select name="sex" class="form-control">
                                    {% for i in sex %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>学院:</h4>
                            <span>
                                <select name="student_college" class="form-control">
                                    {% for i in college %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>手机号码:</h4>
                            <span><input type="text" class="form-control" name="phone" required  autocomplete="off"></span>
                        </li>
                        <li>
                            <h4>入学日期:</h4>
                            <span><input type="text" class="form-control" name="student_come_year" required></span>
                        </li>
                        <li>
                            <h4>省份:</h4>
                            <span><input type="text" class="form-control" name="student_province" required></span>
                        </li>
                        <li>
                            <h4>出生日期:</h4>
                            <span><input type="text" class="form-control" name="student_birthday" required></span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul style="list-style: none">
                        <li>
                            <h4>姓名:</h4>
                            <span><input type="text" class="form-control" name="student_name" required></span>
                        </li>
                        <li>
                            <h4>民族:</h4>
                            <span>
                                <select name="student_nation" class="form-control">
                                    {% for i in nation %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>专业:</h4>
                            <span><input type="text" class="form-control" name="student_major" required></span>
                        </li>
                        <li>
                            <h4>邮件地址:</h4>
                            <span><input type="text" class="form-control" name="email" required></span>
                        </li>
                        <li>
                            <h4>状态:</h4>
                            <span>
                                <select name="student_status" class="form-control">
                                    {% for i in status %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>城市:</h4>
                            <span><input type="text" class="form-control" name="student_city" required></span>
                        </li>
                        <li>
                            <h4>微信号码:</h4>
                            <span><input type="text" class="form-control" name="student_wechat" required></span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4" >
                    <ul style="list-style: none">
                        <li>
                            <h4>年龄:</h4>
                            <span><input type="text" class="form-control" name="student_age" required></span>
                        </li>
                        <li>
                            <h4>政治面貌:</h4>
                            <span>
                                <select name="student_political_status" class="form-control">
                                    {% for i in political_status %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>班级:</h4>
                            <span><input type="text" class="form-control" name="student_class" required></span>
                        </li>
                        <li>
                            <h4>外语:</h4>
                            <span>
                                <select name="student_foreign_language" class="form-control">
                                    {% for i in language %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>毕业高中:</h4>
                            <span><input type="text" class="form-control" name="student_high_school" required></span>
                        </li>
                        <li>
                            <h4>QQ号码:</h4>
                            <span><input type="text" class="form-control" name="student_qq" required></span>
                        </li>
                        <li>
                            <span>
                                <button type="submit" class="btn btn-primary btn-block pull-right" style="margin-top: 40px; width: 100px; margin-right: 40px">提&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp交</button>
                            </span>
                        </li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="footer" style="padding: 25px">
	<p style="text-align: center; color: rgb(128, 153, 175)">版权所有&copy; Copyright 1999-2017  正方软件股份有限公司　　中国·杭州西湖区紫霞街176号 互联网创新创业园2号301</p>
    </div>
</body>
</html>

app/templates/teacher/add_teacher.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8"/>
    <title>添加教师</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body{
            background-color: rgb(240, 240, 240);
        }
    </style>
</head>
<body>
    {% if is_add %}
        <script>
            window.onload=function () {
                alert("添加成功！")
            }
        </script>
    {% endif %}
    <div style="background: #0483d4; border: 1px solid #e7e7e7;line-height: 60px; margin-bottom: 15px">
        <img src="{% static 'image/logo_jw_w2.png' %}" style="padding-left: 80px">
        <span style="color: white; font-size: 25px; vertical-align: middle">添加教师</span>
    </div>
    <!--top_end-->
    <div class="container" style="margin-left: 70px; margin-top: 1px; padding: 0px; margin-right: 70px; width: auto">
        <form action="/add_teacher/" method="post">
            {% csrf_token %}
            <div class="row" style="background: white; margin-top: 15px;">
                <div class="col-md-12" style="border-bottom: 1px solid #eeeeee; font-weight: bold; font-size: 20px; padding: 5px; line-height: 80px;">
                    <center>添加教师</center>
                </div>
                <div class="col-md-4" >
                    <ul style="list-style: none">
                        <li>
                            <h4>工号:</h4>
                            <span><input type="text" class="form-control" name="teacher_id" required autocomplete="off"></span>
                        </li>
                        <li>
                            <h4>性别:</h4>
                            <span>
                                <select name="sex" class="form-control">
                                    {% for i in sex %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>学院:</h4>
                            <span>
                                <select name="teacher_department" class="form-control">
                                    {% for i in college %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>手机号码:</h4>
                            <span><input type="text" class="form-control" name="phone" required  autocomplete="off"></span>
                        </li>
                        <li>
                            <h4>入职日期:</h4>
                            <span><input type="text" class="form-control" name="teacher_come_year" required></span>
                        </li>

                        <li>
                            <h4>出生日期:</h4>
                            <span><input type="text" class="form-control" name="teacher_birthday" required></span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul style="list-style: none">
                        <li>
                            <h4>姓名:</h4>
                            <span><input type="text" class="form-control" name="teacher_name" required></span>
                        </li>
                        <li>
                            <h4>民族:</h4>
                            <span>
                                <select name="teacher_nation" class="form-control">
                                    {% for i in nation %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>职称:</h4>
                            <span>
                                {{ teacher.get_teacher_academic_title_display }}
                                <select name="teacher_academic_title" class="form-control">
                                    {% for i in academic_title %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>邮件地址:</h4>
                            <span><input type="text" class="form-control" name="email" required></span>
                        </li>
                        <li>
                            <h4>省份:</h4>
                            <span><input type="text" class="form-control" name="teacher_province" required></span>
                        </li>

                        <li>
                            <h4>微信号码:</h4>
                            <span><input type="text" class="form-control" name="teacher_wechat" required></span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4" >
                    <ul style="list-style: none">
                        <li>
                            <h4>年龄:</h4>
                            <span><input type="text" class="form-control" name="teacher_age" required></span>
                        </li>
                        <li>
                            <h4>政治面貌:</h4>
                            <span>
                                <select name="teacher_political_status" class="form-control">
                                    {% for i in political_status %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>学位:</h4>
                            <span>
                                <select name="teacher_degree" class="form-control">
                                    {% for i in degree %}
                                        <option value="{{ i }}">{{ i }}</option>
                                    {% endfor %}
                                </select>
                            </span>
                        </li>
                        <li>
                            <h4>毕业院校:</h4>
                            <span><input type="text" class="form-control" name="teacher_graduate_school" required></span>
                        </li>
                        <li>
                            <h4>城市:</h4>
                            <span><input type="text" class="form-control" name="teacher_city" required></span>
                        </li>
                        <li>
                            <h4>QQ号码:</h4>
                            <span><input type="text" class="form-control" name="teacher_qq" required></span>
                        </li>
                    </ul>
                </div>
                <div class="col-md-12" style="border-top: 1px solid #eeeeee; font-weight: bold; font-size: 20px; padding: 5px; line-height: 80px;">
                    <span>
                        <button type="submit" class="btn btn-primary btn-block pull-right" style="margin-top: 20px; margin-bottom: 20px; width: 100px; margin-right: 40px">提&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp交</button>
                    </span>
                </div>
            </div>
        </form>
    </div>
    <div class="footer" style="padding: 25px">
	<p style="text-align: center; color: rgb(128, 153, 175)">版权所有&copy; Copyright 1999-2017  正方软件股份有限公司　　中国·杭州西湖区紫霞街176号 互联网创新创业园2号301</p>
    </div>
</body>
</html>

app/templates/teacher/notice.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8"/>
    <title>通知详情</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body{
            background-color: rgb(240, 240, 240);
        }
    </style>
</head>
<body>
    <div style="background: #0483d4; border: 1px solid #e7e7e7;line-height: 60px; margin-bottom: 15px">
        <img src="{% static 'image/logo_jw_w2.png' %}" style="padding-left: 80px">
        <span style="color: white; font-size: 25px; vertical-align: middle">通知详情</span>
    </div>
    <!--top_end-->
    <div class="container" style="margin-left: 70px; margin-top: 1px; padding: 0px; margin-right: 70px; width: auto; background-color: white; height: 600px;">
        <div class="row">
            <div class="col-md-12" style="line-height: 25px;border: 1px solid #eeeeee;">
                <center style="font-size: 40px;padding-top: 20px" >{{ notice.notice_title }}</center><br>
                <span style="font-size: 15px; padding-right: 80px;" class="pull-right">发布时间: {{ notice.notice_send_time }}</span>
            </div>
            <div class="col-md-12">
                <span style="font-size: 25px;padding: 30px">{{ notice.notice_content|linebreaksbr }} </span>
            </div>
        </div>
    </div>
    <div class="footer" style="padding: 25px">
	<p style="text-align: center; color: rgb(128, 153, 175)">版权所有&copy; Copyright 1999-2017  正方软件股份有限公司　　中国·杭州西湖区紫霞街176号 互联网创新创业园2号301</p>
    </div>
</body>
</html>